Repository brain-tec/server-ux, pull requests merged in 2023-02, with the labels that each got.

#478 Syncing from upstream OCA/server-ux (11.0)
  default_multi_user/i18n/it.po
Labels: 11.0

#479 Syncing from upstream OCA/server-ux (13.0)
  mass_operation_abstract/i18n/it.po
Labels: 13.0

#480 Syncing from upstream OCA/server-ux (14.0)
  default_multi_user/i18n/it.po
  filter_multi_user/i18n/it.po
  mass_operation_abstract/i18n/it.po
Labels: 14.0

#482 Syncing from upstream OCA/server-ux (16.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  base_tier_validation/i18n/base_tier_validation.pot
Labels: 16.0

#483 Syncing from upstream OCA/server-ux (16.0)
  base_tier_validation/i18n/es.po
  base_tier_validation/i18n/es_MX.po
  base_tier_validation/i18n/fr.po
  base_tier_validation/i18n/it.po
  base_tier_validation/i18n/nl_NL.po
  base_tier_validation/i18n/sv.po
  base_tier_validation/i18n/zh_CN.po
Labels: 16.0

#484 Syncing from upstream OCA/server-ux (13.0)
  README.md
  base_action_visibility_restriction/README.rst
  base_action_visibility_restriction/__init__.py
  base_action_visibility_restriction/__manifest__.py
  base_action_visibility_restriction/i18n/base_action_visibility_restriction.pot
  base_action_visibility_restriction/models/__init__.py
  base_action_visibility_restriction/models/ir_actions.py
  base_action_visibility_restriction/readme/CONTRIBUTORS.rst
  base_action_visibility_restriction/readme/DESCRIPTION.rst
  base_action_visibility_restriction/readme/USAGE.rst
  base_action_visibility_restriction/static/description/icon.png
  base_action_visibility_restriction/static/description/index.html
  base_action_visibility_restriction/tests/__init__.py
  base_action_visibility_restriction/tests/test_base_action_visibility_restriction.py
  base_action_visibility_restriction/views/ir_actions_views.xml
  base_ir_actions_report_sequence/README.rst
  base_ir_actions_report_sequence/__init__.py
  base_ir_actions_report_sequence/__manifest__.py
  base_ir_actions_report_sequence/i18n/base_ir_actions_report_sequence.pot
  base_ir_actions_report_sequence/models/__init__.py
  base_ir_actions_report_sequence/models/ir_actions.py
  base_ir_actions_report_sequence/static/description/icon.png
  base_ir_actions_report_sequence/static/description/index.html
  base_ir_actions_report_sequence/views/ir_actions_report_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_action_visibility_restriction/odoo/addons/base_action_visibility_restriction
  setup/base_action_visibility_restriction/setup.py
  setup/base_ir_actions_report_sequence/odoo/addons/base_ir_actions_report_sequence
  setup/base_ir_actions_report_sequence/setup.py
Labels: 13.0

#486 Syncing from upstream OCA/server-ux (16.0)
  base_tier_validation/i18n/tr.po
Labels: 16.0

#489 Syncing from upstream OCA/server-ux (14.0)
  README.md
  base_tier_validation_waiting/README.rst
  base_tier_validation_waiting/__init__.py
  base_tier_validation_waiting/__manifest__.py
  base_tier_validation_waiting/i18n/base_tier_validation_waiting.pot
  base_tier_validation_waiting/models/__init__.py
  base_tier_validation_waiting/models/tier_definition.py
  base_tier_validation_waiting/models/tier_review.py
  base_tier_validation_waiting/models/tier_validation.py
  base_tier_validation_waiting/readme/CONFIGURE.rst
  base_tier_validation_waiting/readme/CONTRIBUTORS.rst
  base_tier_validation_waiting/readme/DESCRIPTION.rst
  base_tier_validation_waiting/readme/DEVELOP.rst
  base_tier_validation_waiting/readme/ROADMAP.rst
  base_tier_validation_waiting/readme/USAGE.rst
  base_tier_validation_waiting/security/ir.model.access.csv
  base_tier_validation_waiting/static/description/icon.png
  base_tier_validation_waiting/static/description/index.html
  base_tier_validation_waiting/static/src/xml/tier_review_template.xml
  base_tier_validation_waiting/tests/__init__.py
  base_tier_validation_waiting/tests/test_tier_validation.py
  base_tier_validation_waiting/views/tier_definition_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_tier_validation_waiting/odoo/addons/base_tier_validation_waiting
  setup/base_tier_validation_waiting/setup.py
Labels: 14.0

#490 Syncing from upstream OCA/server-ux (16.0)
  README.md
  base_tier_validation/__manifest__.py
  base_tier_validation/static/src/js/ir_model.esm.js
  base_tier_validation/static/src/js/main.esm.js
  base_tier_validation/static/src/js/review_group_view.esm.js
  base_tier_validation/static/src/js/review_groups.esm.js
  base_tier_validation/static/src/js/review_notification_handler.esm.js
  base_tier_validation/static/src/js/reviewer_menu_view.esm.js
  base_tier_validation/static/src/js/systray.esm.js
Labels: 16.0

#491 Syncing from upstream OCA/server-ux (16.0)
  README.md
  base_tier_validation/i18n/base_tier_validation.pot
  base_tier_validation/i18n/es.po
  base_tier_validation/i18n/es_MX.po
  base_tier_validation/i18n/fr.po
  base_tier_validation/i18n/it.po
  base_tier_validation/i18n/nl_NL.po
  base_tier_validation/i18n/sv.po
  base_tier_validation/i18n/tr.po
  base_tier_validation/i18n/zh_CN.po
  base_tier_validation_formula/README.rst
  base_tier_validation_formula/__init__.py
  base_tier_validation_formula/__manifest__.py
  base_tier_validation_formula/i18n/base_tier_validation_formula.pot
  base_tier_validation_formula/i18n/es.po
  base_tier_validation_formula/i18n/it.po
  base_tier_validation_formula/i18n/zh_CN.po
  base_tier_validation_formula/models/__init__.py
  base_tier_validation_formula/models/tier_definition.py
  base_tier_validation_formula/models/tier_review.py
  base_tier_validation_formula/models/tier_validation.py
  base_tier_validation_formula/readme/CONTRIBUTORS.rst
  base_tier_validation_formula/readme/CREDITS.rst
  base_tier_validation_formula/readme/DESCRIPTION.rst
  base_tier_validation_formula/readme/USAGE.rst
  base_tier_validation_formula/static/description/icon.png
  base_tier_validation_formula/static/description/index.html
  base_tier_validation_formula/tests/__init__.py
  base_tier_validation_formula/tests/test_tier_validation.py
  base_tier_validation_formula/views/tier_definition_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_tier_validation_formula/odoo/addons/base_tier_validation_formula
  setup/base_tier_validation_formula/setup.py
Labels: 16.0

#492 [t131055] Bypassing check for accountants and superior groups, to be …
  base_tier_validation/__manifest__.py
  base_tier_validation/models/tier_validation.py
Labels: enhancement, 15.0.project_gr_646

#493 [t131055] Pre-commit fixes
  base_tier_validation/__manifest__.py
  base_tier_validation/models/tier_validation.py
Labels: 15.0.project_gr_646
